language: python
env:
  global:
    - PATH=$PATH:/tmp/bin
# matrix:
#   - BROWSER=firefox
#   - BROWSER=chrome
python:
  # "2.6"
  - "2.7"
install:
  - "/home/travis/virtualenv/python2.7/bin/python setup.py install"
  # "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"
  # "sudo /bin/sh -c 'echo \"deb http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list'"
  # "sudo apt-get update"
  # "sudo apt-get install google-chrome-stable"
  # Install Google Chrome
 #- "sudo apt-get -f install"
 #- "wget https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb"
 #- "sudo apt-get install libgconf2-4"
 #- "sudo dpkg -i google-chrome*.deb"
  # Install the Google Chrome webdriver
 #- "mkdir /tmp/bin"
 #- "wget https://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip"
 #- "unzip chromedriver_linux32_23.0.1240.0.zip"
 #- "mv chromedriver /tmp/bin"
  - "pip install -r docs/requirements.txt --use-mirrors"
  - "pip install -r example_project/requirements.txt --use-mirrors"
before_script:
  # Setup headless X per http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "export BROWSER=FIREFOX"
  - "PATH=$PATH:/tmp/bin sudo /home/travis/virtualenv/python2.7/bin/python example_project/manage.py harvest -A dajaxice,south,editlive"
